package codegen_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"kaizengo/packages/sdk-go/appspec"
	"kaizengo/packages/sdk-go/codegen"
)

func TestGenerateLocaleTemplate(t *testing.T) {
	dir := t.TempDir()
	spec, err := appspec.Parse([]byte(`
name: demo
title: Demo
summary: Demo app
nav:
  labelKey: nav.demo
models:
  - name: item
    fields:
      - name: title
        type: string
        required: true
      - name: status
        type: enum
        values: [open, closed]
        default: open
    search:
      collection: demo.item
      fields: [title]
menus:
  - id: items
    labelKey: demo.menu.items
    view: Items
views:
  - name: Items
    type: page
`))
	if err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(dir, "views"), 0o755); err != nil {
		t.Fatal(err)
	}
	view := `<script lang="ts">
  import { t } from '@kaizengo/sdk-svelte/ui'
</script>
<h1>{t('demo.custom.title')}</h1>
<KTable emptyKey="demo.empty.items" />
`
	if err := os.WriteFile(filepath.Join(dir, "views", "Items.svelte"), []byte(view), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "gql.go"), []byte(`package demo
func labels() { _ = labelField("demo.locale") }
func hook() { _ = i18n.Error("demo.error.denied") }
`), 0o644); err != nil {
		t.Fatal(err)
	}

	n, err := codegen.GenerateLocaleTemplate(spec, dir)
	if err != nil {
		t.Fatal(err)
	}
	if n < 10 {
		t.Fatalf("expected several keys, got %d", n)
	}
	src, err := os.ReadFile(filepath.Join(dir, "locale", "template.pot"))
	if err != nil {
		t.Fatal(err)
	}
	out := string(src)
	for _, want := range []string{
		"# Generated by kaizengo gen-types. DO NOT EDIT.",
		`msgid "nav.demo"`,
		`msgid "demo.title"`,
		`msgid "demo.field.title"`,
		`msgid "demo.enum.item.status.open"`,
		`msgid "demo.menu.items"`,
		`msgid "demo.item.search"`,
		`msgid "demo.custom.title"`,
		`msgid "demo.empty.items"`,
		`msgid "demo.locale"`,
		`msgid "demo.error.denied"`,
		`msgstr ""`,
	} {
		if !strings.Contains(out, want) {
			t.Fatalf("template.pot missing %q:\n%s", want, out)
		}
	}
	if strings.Contains(out, "POT-Creation-Date") {
		t.Fatal("template.pot must be deterministic (no POT-Creation-Date)")
	}
}

func TestGenerateLocaleTemplateSkipsDisabledI18n(t *testing.T) {
	dir := t.TempDir()
	spec, err := appspec.Parse([]byte(`
name: demo
title: Demo
summary: Demo app
i18n: false
`))
	if err != nil {
		t.Fatal(err)
	}
	n, err := codegen.GenerateLocaleTemplate(spec, dir)
	if err != nil {
		t.Fatal(err)
	}
	if n != 0 {
		t.Fatalf("expected 0 keys, got %d", n)
	}
	if _, err := os.Stat(filepath.Join(dir, "locale", "template.pot")); !os.IsNotExist(err) {
		t.Fatal("should not write template.pot when i18n is disabled")
	}
}
