package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"kaizengo/packages/sdk-go/appspec"
)

// GenerateAppTypes writes apps/<app>/__types__/<model>.go for each model in the spec.
func GenerateAppTypes(spec appspec.AppSpec, appDir string) error {
	outDir := filepath.Join(appDir, "__types__")
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}
	if len(spec.Models) == 0 {
		return writeEmptyTypes(outDir)
	}
	for _, model := range spec.Models {
		src, err := renderModelFile(spec.Name, model)
		if err != nil {
			return fmt.Errorf("model %s: %w", model.Name, err)
		}
		path := filepath.Join(outDir, model.Name+".go")
		if err := os.WriteFile(path, src, 0o644); err != nil {
			return err
		}
	}
	return pruneStaleModelFiles(outDir, spec.Models)
}

func writeEmptyTypes(outDir string) error {
	src := []byte("// Code generated by kaizengo gen-types; DO NOT EDIT.\n\npackage types\n")
	return os.WriteFile(filepath.Join(outDir, "doc.go"), src, 0o644)
}

func pruneStaleModelFiles(outDir string, models []appspec.ModelSpec) error {
	keep := map[string]struct{}{}
	for _, m := range models {
		keep[m.Name+".go"] = struct{}{}
	}
	entries, err := os.ReadDir(outDir)
	if err != nil {
		return err
	}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") {
			continue
		}
		if e.Name() == "doc.go" {
			continue
		}
		if _, ok := keep[e.Name()]; ok {
			continue
		}
		path := filepath.Join(outDir, e.Name())
		b, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if bytes.Contains(b, []byte("Code generated by kaizengo gen-types")) {
			if err := os.Remove(path); err != nil {
				return err
			}
		}
	}
	return nil
}

type modelFileData struct {
	App        string
	Model      string
	StructName string
	NeedsTime  bool
	Enums      []enumData
	Fields     []fieldData
}

type enumData struct {
	TypeName string
	Field    string
	Values   []enumValue
}

type enumValue struct {
	Const string
	Value string
}

type fieldData struct {
	Name     string
	JSONName string
	GoType   string
	Comment  string
}

func renderModelFile(app string, model appspec.ModelSpec) ([]byte, error) {
	data := modelFileData{
		App:        app,
		Model:      model.Name,
		StructName: pascal(model.Name),
		NeedsTime:  true,
		Fields: []fieldData{
			{Name: "ID", JSONName: "id", GoType: "string"},
			{Name: "OrgID", JSONName: "orgId", GoType: "string"},
			{Name: "AuthorID", JSONName: "authorId", GoType: "string"},
			{Name: "Deleted", JSONName: "deleted", GoType: "bool"},
			{Name: "CreatedAt", JSONName: "createdAt", GoType: "time.Time"},
			{Name: "UpdatedAt", JSONName: "updatedAt", GoType: "time.Time"},
		},
	}
	for _, f := range model.Fields {
		fd := fieldData{
			Name:     fieldGoName(f.Name),
			JSONName: f.Name,
			GoType:   goType(f, model.Name),
		}
		var notes []string
		if f.Readonly {
			notes = append(notes, "readonly")
		}
		if f.Default != nil {
			notes = append(notes, fmt.Sprintf("default=%v", f.Default))
		}
		if f.Required {
			notes = append(notes, "required")
		}
		if len(notes) > 0 {
			fd.Comment = strings.Join(notes, ", ")
		}
		data.Fields = append(data.Fields, fd)
		if f.IsEnum() && !f.IsRelation() {
			data.Enums = append(data.Enums, buildEnum(model.Name, f))
		}
	}

	var buf bytes.Buffer
	if err := modelTmpl.Execute(&buf, data); err != nil {
		return nil, err
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format: %w\n----\n%s", err, buf.String())
	}
	return formatted, nil
}

func buildEnum(model string, f appspec.FieldSpec) enumData {
	typeName := f.EnumTypeName(model)
	out := enumData{TypeName: typeName, Field: f.Name}
	for _, v := range f.Values {
		out.Values = append(out.Values, enumValue{
			Const: typeName + pascal(v),
			Value: v,
		})
	}
	return out
}

func goType(f appspec.FieldSpec, model string) string {
	if f.IsEnum() && !f.IsRelation() {
		return f.EnumTypeName(model)
	}
	switch f.CanonicalType() {
	case appspec.TypeInt:
		return "int"
	case appspec.TypeNumber:
		return "float64"
	case appspec.TypeBool:
		return "bool"
	case appspec.TypeDatetime:
		return "time.Time"
	case appspec.TypeMany2Many, appspec.TypeOne2Many:
		return "[]string"
	default:
		return "string"
	}
}

// fieldGoName maps camelCase / snake_case field names to exported Go names.
func fieldGoName(name string) string {
	switch name {
	case "id":
		return "ID"
	case "orgId":
		return "OrgID"
	case "authorId":
		return "AuthorID"
	case "parentId":
		return "ParentID"
	case "userId":
		return "UserID"
	default:
		return pascal(name)
	}
}

func pascal(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool {
		return r == '_' || r == '-' || r == ' '
	})
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		runes := []rune(p)
		start := 0
		for i := 1; i < len(runes); i++ {
			if runes[i] >= 'A' && runes[i] <= 'Z' && (runes[i-1] < 'A' || runes[i-1] > 'Z') {
				seg := string(runes[start:i])
				b.WriteString(strings.ToUpper(seg[:1]) + seg[1:])
				start = i
			}
		}
		seg := string(runes[start:])
		b.WriteString(strings.ToUpper(seg[:1]) + seg[1:])
	}
	return b.String()
}

var modelTmpl = template.Must(template.New("model").Parse(`// Code generated by kaizengo gen-types from apps/{{.App}}/app.yaml; DO NOT EDIT.

package types

{{if .NeedsTime}}import "time"
{{end}}
{{range $e := .Enums}}
// {{$e.TypeName}} is the enum for {{$.Model}}.{{$e.Field}}.
type {{$e.TypeName}} string

const (
{{- range $e.Values}}
	{{.Const}} {{$e.TypeName}} = "{{.Value}}"
{{- end}}
)

// Valid reports whether v is a known {{$e.TypeName}} value.
func (v {{$e.TypeName}}) Valid() bool {
	switch v {
	case {{range $i, $val := $e.Values}}{{if $i}}, {{end}}{{$val.Const}}{{end}}:
		return true
	default:
		return false
	}
}
{{end}}
// {{.StructName}} is the generated type for {{.App}}.{{.Model}}.
type {{.StructName}} struct {
{{- range .Fields}}
	{{.Name}} {{.GoType}} ` + "`" + `json:"{{.JSONName}}"` + "`" + `{{if .Comment}} // {{.Comment}}{{end}}
{{- end}}
}
`))
