// Code generated by kaizengo gen-types from apps/hellospec/app.yaml; DO NOT EDIT.

package types

import "time"

// Greeting is the generated type for hellospec.greeting.
type Greeting struct {
	ID        string    `json:"id"`
	OrgID     string    `json:"orgId"`
	AuthorID  string    `json:"authorId"`
	Deleted   bool      `json:"deleted"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	Message   string    `json:"message"` // required
}
