/** Spec-driven CQRS UI — re-exports from `@/components/k`. */

export {
  KAppStatus,
  KForm,
  KFormField,
  KTable,
  KTableView,
  KChart,
  KChartView,
  KChartDesigner,
  DEFAULT_CHART_TYPES,
  chartConfigFromPreset,
  KPivot,
  KPivotView,
  KKanban,
  KKanbanBoard,
  KCollection,
  KPagination,
  KSearch,
  KQueryShell,
  getKFormContext,
  useKForm,
  useKQuery,
  usePaginationParams,
  useKSearchParams,
  useCollectionViewParam,
  useChartUrlState,
  usePivotUrlState,
  enableConfig,
  DEFAULT_PAGE_SIZE,
  DEFAULT_PAGE_SIZE_OPTIONS,
  sliceItems,
  totalPages,
  encodeDomain,
  decodeDomain,
  serializeLeaves,
  extractLeaves,
  opsForFieldType,
  EMPTY_SEARCH,
  listSearchTemplates,
  saveSearchTemplate,
  deleteSearchTemplate,
  type KKanbanColumn,
  type KKanbanPaginationConfig,
  type KKanbanProps,
  type KKanbanSearchConfig,
  type KKanbanBoardProps,
  type KCollectionChartConfig,
  type KCollectionFilter,
  type KCollectionGroupBy,
  type KCollectionPaginationConfig,
  type KCollectionPivotConfig,
  type KCollectionProps,
  type KCollectionSearchConfig,
  type KCollectionView,
  type KChartConfig,
  type KChartMeasure,
  type KChartPaginationConfig,
  type KChartProps,
  type KChartSearchConfig,
  type KChartType,
  type KChartViewProps,
  type KPivotFieldOption,
  type KPivotMeasure,
  type KPivotPaginationConfig,
  type KPivotProps,
  type KPivotSearchConfig,
  type KPivotViewProps,
  type KTablePaginationConfig,
  type KTableSearchConfig,
  type KTableViewProps,
  type KPaginationProps,
  type KSearchProps,
  type KQueryShellProps,
  type KQueryPaginationConfig,
  type KQuerySearchConfig,
  type UseKQueryOptions,
  type UseKQueryResult,
  type PaginationParamsOptions,
  type PaginationState,
  type KSearchParamsOptions,
  type Domain,
  type DomainLeaf,
  type DomainOp,
  type SearchField,
  type SearchState,
  type SearchTemplate,
  type KFormActionsContext,
  type KFormContext,
  type KFormFieldContext,
} from '@/components/k'
