/** Spec-driven CQRS UI — re-exports from `@/components/k`. */

export {
  KAppStatus,
  KForm,
  KFormField,
  KTable,
  KTableView,
  KKanban,
  KKanbanBoard,
  KCollection,
  KPagination,
  KSearch,
  KQueryShell,
  getKFormContext,
  useKForm,
  useKQuery,
  usePaginationParams,
  useKSearchParams,
  enableConfig,
  DEFAULT_PAGE_SIZE,
  DEFAULT_PAGE_SIZE_OPTIONS,
  sliceItems,
  totalPages,
  encodeDomain,
  decodeDomain,
  serializeLeaves,
  extractLeaves,
  opsForFieldType,
  EMPTY_SEARCH,
  listSearchTemplates,
  saveSearchTemplate,
  deleteSearchTemplate,
  renameSearchTemplate,
  type KKanbanColumn,
  type KKanbanPaginationConfig,
  type KKanbanProps,
  type KKanbanSearchConfig,
  type KKanbanBoardProps,
  type KCollectionFilter,
  type KCollectionGroupBy,
  type KCollectionPaginationConfig,
  type KCollectionProps,
  type KCollectionSearchConfig,
  type KCollectionView,
  type KTablePaginationConfig,
  type KTableSearchConfig,
  type KTableViewProps,
  type KPaginationProps,
  type KSearchProps,
  type KQueryShellProps,
  type KQueryPaginationConfig,
  type KQuerySearchConfig,
  type UseKQueryOptions,
  type UseKQueryResult,
  type PaginationParamsOptions,
  type PaginationState,
  type KSearchParamsOptions,
  type Domain,
  type DomainLeaf,
  type DomainOp,
  type SearchField,
  type SearchState,
  type SearchTemplate,
  type KFormActionsContext,
  type KFormContext,
  type KFormFieldContext,
} from '@/components/k'
