// Code generated by kaizengo gen-types from apps/identity/app.yaml; DO NOT EDIT.

package types

import "time"

// Membership is the generated type for identity.membership.
type Membership struct {
	ID            string    `json:"id"`
	OrgID         string    `json:"orgId"`
	AuthorID      string    `json:"authorId"`
	Deleted       bool      `json:"deleted"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
	UserID        string    `json:"userId"`    // required
	OrgUnitId     string    `json:"orgUnitId"` // required
	Role          string    `json:"role"`
	EffectiveFrom time.Time `json:"effectiveFrom"`
	EffectiveTo   time.Time `json:"effectiveTo"`
}
