// Code generated by kaizengo gen-types from apps/identity/app.yaml; DO NOT EDIT.

package types

import "time"

// OrgUnitType is the enum for org_unit.type.
type OrgUnitType string

const (
	OrgUnitTypeBusinessUnit OrgUnitType = "business_unit"
	OrgUnitTypeDepartment   OrgUnitType = "department"
	OrgUnitTypeLocation     OrgUnitType = "location"
	OrgUnitTypeTeam         OrgUnitType = "team"
	OrgUnitTypePosition     OrgUnitType = "position"
)

// Valid reports whether v is a known OrgUnitType value.
func (v OrgUnitType) Valid() bool {
	switch v {
	case OrgUnitTypeBusinessUnit, OrgUnitTypeDepartment, OrgUnitTypeLocation, OrgUnitTypeTeam, OrgUnitTypePosition:
		return true
	default:
		return false
	}
}

// OrgUnit is the generated type for identity.org_unit.
type OrgUnit struct {
	ID        string      `json:"id"`
	OrgID     string      `json:"orgId"`
	AuthorID  string      `json:"authorId"`
	Deleted   bool        `json:"deleted"`
	CreatedAt time.Time   `json:"createdAt"`
	UpdatedAt time.Time   `json:"updatedAt"`
	Name      string      `json:"name"` // required
	Type      OrgUnitType `json:"type"` // required
	ParentID  string      `json:"parentId"`
}
