// Code generated by kaizengo gen-types from apps/identity/app.yaml; DO NOT EDIT.

package types

import "time"

// Organization is the generated type for identity.organization.
type Organization struct {
	ID        string    `json:"id"`
	OrgID     string    `json:"orgId"`
	AuthorID  string    `json:"authorId"`
	Deleted   bool      `json:"deleted"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	Name      string    `json:"name"` // required
	Slug      string    `json:"slug"` // required
}
