// Code generated by kaizengo gen-types from apps/identity/app.yaml; DO NOT EDIT.

package types

import "time"

// UserStatus is the enum for user.status.
type UserStatus string

const (
	UserStatusActive    UserStatus = "active"
	UserStatusSuspended UserStatus = "suspended"
	UserStatusInvited   UserStatus = "invited"
)

// Valid reports whether v is a known UserStatus value.
func (v UserStatus) Valid() bool {
	switch v {
	case UserStatusActive, UserStatusSuspended, UserStatusInvited:
		return true
	default:
		return false
	}
}

// User is the generated type for identity.user.
type User struct {
	ID        string     `json:"id"`
	OrgID     string     `json:"orgId"`
	AuthorID  string     `json:"authorId"`
	Deleted   bool       `json:"deleted"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
	Name      string     `json:"name"`   // required
	Email     string     `json:"email"`  // required
	Status    UserStatus `json:"status"` // default=active
}
