// Code generated by kaizengo gen-types from apps/permissions/app.yaml; DO NOT EDIT.

package types

import "time"

// AclEntryEffect is the enum for acl_entry.effect.
type AclEntryEffect string

const (
	AclEntryEffectAllow AclEntryEffect = "allow"
	AclEntryEffectDeny  AclEntryEffect = "deny"
)

// Valid reports whether v is a known AclEntryEffect value.
func (v AclEntryEffect) Valid() bool {
	switch v {
	case AclEntryEffectAllow, AclEntryEffectDeny:
		return true
	default:
		return false
	}
}

// AclEntry is the generated type for permissions.acl_entry.
type AclEntry struct {
	ID        string         `json:"id"`
	OrgID     string         `json:"orgId"`
	AuthorID  string         `json:"authorId"`
	Deleted   bool           `json:"deleted"`
	CreatedAt time.Time      `json:"createdAt"`
	UpdatedAt time.Time      `json:"updatedAt"`
	Name      string         `json:"name"`     // required
	RoleId    string         `json:"roleId"`   // required
	Effect    AclEntryEffect `json:"effect"`   // default=allow, required
	Resource  string         `json:"resource"` // required
	Actions   string         `json:"actions"`  // default=["*"], required
	Fields    string         `json:"fields"`   // default="*", required
	Domain    string         `json:"domain"`   // default=[], required
	Priority  int            `json:"priority"` // default=0, required
	Active    bool           `json:"active"`   // default=true, required
}
