// Code generated by kaizengo gen-types from apps/permissions/app.yaml; DO NOT EDIT.

package types

import "time"

// Role is the generated type for permissions.role.
type Role struct {
	ID          string    `json:"id"`
	OrgID       string    `json:"orgId"`
	AuthorID    string    `json:"authorId"`
	Deleted     bool      `json:"deleted"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
	Name        string    `json:"name"`  // required
	Label       string    `json:"label"` // required
	Description string    `json:"description"`
	Active      bool      `json:"active"` // default=true, required
}
