// Code generated by kaizengo gen-types from apps/permissions/app.yaml; DO NOT EDIT.

package types

import "time"

// UserRole is the generated type for permissions.user_role.
type UserRole struct {
	ID        string    `json:"id"`
	OrgID     string    `json:"orgId"`
	AuthorID  string    `json:"authorId"`
	Deleted   bool      `json:"deleted"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	UserID    string    `json:"userId"` // required
	RoleId    string    `json:"roleId"` // required
}
