// Code generated by kaizengo gen-types from apps/permissions/app.yaml; DO NOT EDIT.

package types

import "time"

// UserRoleRole is the enum for user_role.role.
type UserRoleRole string

const (
	UserRoleRoleAdmin  UserRoleRole = "admin"
	UserRoleRoleMember UserRoleRole = "member"
)

// Valid reports whether v is a known UserRoleRole value.
func (v UserRoleRole) Valid() bool {
	switch v {
	case UserRoleRoleAdmin, UserRoleRoleMember:
		return true
	default:
		return false
	}
}

// UserRole is the generated type for permissions.user_role.
type UserRole struct {
	ID        string       `json:"id"`
	OrgID     string       `json:"orgId"`
	AuthorID  string       `json:"authorId"`
	Deleted   bool         `json:"deleted"`
	CreatedAt time.Time    `json:"createdAt"`
	UpdatedAt time.Time    `json:"updatedAt"`
	UserID    string       `json:"userId"` // required
	Role      UserRoleRole `json:"role"`   // required
}
