// Code generated by kaizengo gen-types from apps/inventory/app.yaml; DO NOT EDIT.

package types

import "time"

// AdjustmentReason is the enum for adjustment.reason.
type AdjustmentReason string

const (
	AdjustmentReasonCycleCount AdjustmentReason = "cycle_count"
	AdjustmentReasonPhysical   AdjustmentReason = "physical"
	AdjustmentReasonDamage     AdjustmentReason = "damage"
	AdjustmentReasonFound      AdjustmentReason = "found"
	AdjustmentReasonDataFix    AdjustmentReason = "data_fix"
)

// Valid reports whether v is a known AdjustmentReason value.
func (v AdjustmentReason) Valid() bool {
	switch v {
	case AdjustmentReasonCycleCount, AdjustmentReasonPhysical, AdjustmentReasonDamage, AdjustmentReasonFound, AdjustmentReasonDataFix:
		return true
	default:
		return false
	}
}

// AdjustmentState is the enum for adjustment.state.
type AdjustmentState string

const (
	AdjustmentStateDraft     AdjustmentState = "draft"
	AdjustmentStateConfirmed AdjustmentState = "confirmed"
	AdjustmentStateDone      AdjustmentState = "done"
)

// Valid reports whether v is a known AdjustmentState value.
func (v AdjustmentState) Valid() bool {
	switch v {
	case AdjustmentStateDraft, AdjustmentStateConfirmed, AdjustmentStateDone:
		return true
	default:
		return false
	}
}

// Adjustment is the generated type for inventory.adjustment.
type Adjustment struct {
	ID         string           `json:"id"`
	OrgID      string           `json:"orgId"`
	AuthorID   string           `json:"authorId"`
	Deleted    bool             `json:"deleted"`
	CreatedAt  time.Time        `json:"createdAt"`
	UpdatedAt  time.Time        `json:"updatedAt"`
	Name       string           `json:"name"`
	LocationId string           `json:"locationId"` // required
	VariantId  string           `json:"variantId"`  // required
	LotId      string           `json:"lotId"`
	Reason     AdjustmentReason `json:"reason"`     // default=cycle_count
	CountedQty float64          `json:"countedQty"` // required
	SystemQty  float64          `json:"systemQty"`  // default=0
	State      AdjustmentState  `json:"state"`      // default=draft
	Notes      string           `json:"notes"`
}
