// Code generated by kaizengo gen-types from apps/inventory/app.yaml; DO NOT EDIT.

package types

import "time"

// AttributeAttributeType is the enum for attribute.attributeType.
type AttributeAttributeType string

const (
	AttributeAttributeTypeSelect AttributeAttributeType = "select"
	AttributeAttributeTypeText   AttributeAttributeType = "text"
	AttributeAttributeTypeNumber AttributeAttributeType = "number"
)

// Valid reports whether v is a known AttributeAttributeType value.
func (v AttributeAttributeType) Valid() bool {
	switch v {
	case AttributeAttributeTypeSelect, AttributeAttributeTypeText, AttributeAttributeTypeNumber:
		return true
	default:
		return false
	}
}

// Attribute is the generated type for inventory.attribute.
type Attribute struct {
	ID            string                 `json:"id"`
	OrgID         string                 `json:"orgId"`
	AuthorID      string                 `json:"authorId"`
	Deleted       bool                   `json:"deleted"`
	CreatedAt     time.Time              `json:"createdAt"`
	UpdatedAt     time.Time              `json:"updatedAt"`
	Name          string                 `json:"name"`          // required
	Code          string                 `json:"code"`          // required
	AttributeType AttributeAttributeType `json:"attributeType"` // default=select
	Values        []string               `json:"values"`
}
