// Code generated by kaizengo gen-types from apps/inventory/app.yaml; DO NOT EDIT.

package types

import "time"

// CostLayer is the generated type for inventory.cost_layer.
type CostLayer struct {
	ID           string    `json:"id"`
	OrgID        string    `json:"orgId"`
	AuthorID     string    `json:"authorId"`
	Deleted      bool      `json:"deleted"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
	VariantId    string    `json:"variantId"` // required
	LotId        string    `json:"lotId"`
	Quantity     float64   `json:"quantity"`    // default=0
	OriginalQty  float64   `json:"originalQty"` // default=0
	UnitCost     float64   `json:"unitCost"`    // default=0
	ReceivedAt   time.Time `json:"receivedAt"`
	SourceMoveId string    `json:"sourceMoveId"`
}
