// Code generated by kaizengo gen-types from apps/inventory/app.yaml; DO NOT EDIT.

package types

import "time"

// IntegrationKind is the enum for integration.kind.
type IntegrationKind string

const (
	IntegrationKindWebhook  IntegrationKind = "webhook"
	IntegrationKindSap      IntegrationKind = "sap"
	IntegrationKindNetsuite IntegrationKind = "netsuite"
	IntegrationKindOdoo     IntegrationKind = "odoo"
	IntegrationKindShopify  IntegrationKind = "shopify"
	IntegrationKindCrm      IntegrationKind = "crm"
	IntegrationKindCustom   IntegrationKind = "custom"
)

// Valid reports whether v is a known IntegrationKind value.
func (v IntegrationKind) Valid() bool {
	switch v {
	case IntegrationKindWebhook, IntegrationKindSap, IntegrationKindNetsuite, IntegrationKindOdoo, IntegrationKindShopify, IntegrationKindCrm, IntegrationKindCustom:
		return true
	default:
		return false
	}
}

// Integration is the generated type for inventory.integration.
type Integration struct {
	ID        string          `json:"id"`
	OrgID     string          `json:"orgId"`
	AuthorID  string          `json:"authorId"`
	Deleted   bool            `json:"deleted"`
	CreatedAt time.Time       `json:"createdAt"`
	UpdatedAt time.Time       `json:"updatedAt"`
	Name      string          `json:"name"` // required
	Kind      IntegrationKind `json:"kind"` // required
	Endpoint  string          `json:"endpoint"`
	Events    string          `json:"events"`
	Secret    string          `json:"secret"`
	Active    bool            `json:"active"` // default=true
	Config    string          `json:"config"`
}
