// Code generated by kaizengo gen-types from apps/inventory/app.yaml; DO NOT EDIT.

package types

import "time"

// IotDeviceDeviceType is the enum for iot_device.deviceType.
type IotDeviceDeviceType string

const (
	IotDeviceDeviceTypeBarcodeScanner  IotDeviceDeviceType = "barcode_scanner"
	IotDeviceDeviceTypeRfidReader      IotDeviceDeviceType = "rfid_reader"
	IotDeviceDeviceTypeMobile          IotDeviceDeviceType = "mobile"
	IotDeviceDeviceTypeMqttSensor      IotDeviceDeviceType = "mqtt_sensor"
	IotDeviceDeviceTypeBluetoothSensor IotDeviceDeviceType = "bluetooth_sensor"
)

// Valid reports whether v is a known IotDeviceDeviceType value.
func (v IotDeviceDeviceType) Valid() bool {
	switch v {
	case IotDeviceDeviceTypeBarcodeScanner, IotDeviceDeviceTypeRfidReader, IotDeviceDeviceTypeMobile, IotDeviceDeviceTypeMqttSensor, IotDeviceDeviceTypeBluetoothSensor:
		return true
	default:
		return false
	}
}

// IotDeviceStatus is the enum for iot_device.status.
type IotDeviceStatus string

const (
	IotDeviceStatusOnline   IotDeviceStatus = "online"
	IotDeviceStatusOffline  IotDeviceStatus = "offline"
	IotDeviceStatusDisabled IotDeviceStatus = "disabled"
)

// Valid reports whether v is a known IotDeviceStatus value.
func (v IotDeviceStatus) Valid() bool {
	switch v {
	case IotDeviceStatusOnline, IotDeviceStatusOffline, IotDeviceStatusDisabled:
		return true
	default:
		return false
	}
}

// IotDevice is the generated type for inventory.iot_device.
type IotDevice struct {
	ID         string              `json:"id"`
	OrgID      string              `json:"orgId"`
	AuthorID   string              `json:"authorId"`
	Deleted    bool                `json:"deleted"`
	CreatedAt  time.Time           `json:"createdAt"`
	UpdatedAt  time.Time           `json:"updatedAt"`
	Name       string              `json:"name"`       // required
	DeviceType IotDeviceDeviceType `json:"deviceType"` // required
	Identifier string              `json:"identifier"` // required
	LocationId string              `json:"locationId"`
	Status     IotDeviceStatus     `json:"status"` // default=offline
	Config     string              `json:"config"`
	LastSeen   time.Time           `json:"lastSeen"`
}
