// Code generated by kaizengo gen-types from apps/inventory/app.yaml; DO NOT EDIT.

package types

import "time"

// LocationLocationType is the enum for location.locationType.
type LocationLocationType string

const (
	LocationLocationTypeWarehouse  LocationLocationType = "warehouse"
	LocationLocationTypeZone       LocationLocationType = "zone"
	LocationLocationTypeAisle      LocationLocationType = "aisle"
	LocationLocationTypeRack       LocationLocationType = "rack"
	LocationLocationTypeShelf      LocationLocationType = "shelf"
	LocationLocationTypeBin        LocationLocationType = "bin"
	LocationLocationTypeSupplier   LocationLocationType = "supplier"
	LocationLocationTypeCustomer   LocationLocationType = "customer"
	LocationLocationTypeTransit    LocationLocationType = "transit"
	LocationLocationTypeScrap      LocationLocationType = "scrap"
	LocationLocationTypeInventory  LocationLocationType = "inventory"
	LocationLocationTypeQuarantine LocationLocationType = "quarantine"
	LocationLocationTypeProduction LocationLocationType = "production"
)

// Valid reports whether v is a known LocationLocationType value.
func (v LocationLocationType) Valid() bool {
	switch v {
	case LocationLocationTypeWarehouse, LocationLocationTypeZone, LocationLocationTypeAisle, LocationLocationTypeRack, LocationLocationTypeShelf, LocationLocationTypeBin, LocationLocationTypeSupplier, LocationLocationTypeCustomer, LocationLocationTypeTransit, LocationLocationTypeScrap, LocationLocationTypeInventory, LocationLocationTypeQuarantine, LocationLocationTypeProduction:
		return true
	default:
		return false
	}
}

// LocationUsage is the enum for location.usage.
type LocationUsage string

const (
	LocationUsageInternal LocationUsage = "internal"
	LocationUsageVirtual  LocationUsage = "virtual"
)

// Valid reports whether v is a known LocationUsage value.
func (v LocationUsage) Valid() bool {
	switch v {
	case LocationUsageInternal, LocationUsageVirtual:
		return true
	default:
		return false
	}
}

// Location is the generated type for inventory.location.
type Location struct {
	ID           string               `json:"id"`
	OrgID        string               `json:"orgId"`
	AuthorID     string               `json:"authorId"`
	Deleted      bool                 `json:"deleted"`
	CreatedAt    time.Time            `json:"createdAt"`
	UpdatedAt    time.Time            `json:"updatedAt"`
	Name         string               `json:"name"`         // required
	Code         string               `json:"code"`         // required
	LocationType LocationLocationType `json:"locationType"` // required
	ParentID     string               `json:"parentId"`
	Usage        LocationUsage        `json:"usage"` // default=internal
	Barcode      string               `json:"barcode"`
	Active       bool                 `json:"active"` // default=true
}
