// Code generated by kaizengo gen-types from apps/inventory/app.yaml; DO NOT EDIT.

package types

import "time"

// PickingPickingType is the enum for picking.pickingType.
type PickingPickingType string

const (
	PickingPickingTypeIncoming PickingPickingType = "incoming"
	PickingPickingTypeOutgoing PickingPickingType = "outgoing"
	PickingPickingTypeInternal PickingPickingType = "internal"
	PickingPickingTypeReturn   PickingPickingType = "return"
)

// Valid reports whether v is a known PickingPickingType value.
func (v PickingPickingType) Valid() bool {
	switch v {
	case PickingPickingTypeIncoming, PickingPickingTypeOutgoing, PickingPickingTypeInternal, PickingPickingTypeReturn:
		return true
	default:
		return false
	}
}

// PickingState is the enum for picking.state.
type PickingState string

const (
	PickingStateDraft     PickingState = "draft"
	PickingStateConfirmed PickingState = "confirmed"
	PickingStateAssigned  PickingState = "assigned"
	PickingStateDone      PickingState = "done"
	PickingStateCancelled PickingState = "cancelled"
)

// Valid reports whether v is a known PickingState value.
func (v PickingState) Valid() bool {
	switch v {
	case PickingStateDraft, PickingStateConfirmed, PickingStateAssigned, PickingStateDone, PickingStateCancelled:
		return true
	default:
		return false
	}
}

// PickingQcStatus is the enum for picking.qcStatus.
type PickingQcStatus string

const (
	PickingQcStatusPending PickingQcStatus = "pending"
	PickingQcStatusPassed  PickingQcStatus = "passed"
	PickingQcStatusFailed  PickingQcStatus = "failed"
	PickingQcStatusSkipped PickingQcStatus = "skipped"
)

// Valid reports whether v is a known PickingQcStatus value.
func (v PickingQcStatus) Valid() bool {
	switch v {
	case PickingQcStatusPending, PickingQcStatusPassed, PickingQcStatusFailed, PickingQcStatusSkipped:
		return true
	default:
		return false
	}
}

// Picking is the generated type for inventory.picking.
type Picking struct {
	ID               string             `json:"id"`
	OrgID            string             `json:"orgId"`
	AuthorID         string             `json:"authorId"`
	Deleted          bool               `json:"deleted"`
	CreatedAt        time.Time          `json:"createdAt"`
	UpdatedAt        time.Time          `json:"updatedAt"`
	Name             string             `json:"name"`
	PickingType      PickingPickingType `json:"pickingType"` // required
	State            PickingState       `json:"state"`       // default=draft
	SourceLocationId string             `json:"sourceLocationId"`
	DestLocationId   string             `json:"destLocationId"`
	ScheduledDate    time.Time          `json:"scheduledDate"`
	DoneDate         time.Time          `json:"doneDate"`
	Origin           string             `json:"origin"`
	PartnerName      string             `json:"partnerName"`
	QcStatus         PickingQcStatus    `json:"qcStatus"` // default=skipped
	Wave             string             `json:"wave"`
	Batch            string             `json:"batch"`
	Notes            string             `json:"notes"`
	Moves            []string           `json:"moves"`
}
