// Code generated by kaizengo gen-types from apps/inventory/app.yaml; DO NOT EDIT.

package types

import "time"

// ProductVariantStatus is the enum for product_variant.status.
type ProductVariantStatus string

const (
	ProductVariantStatusActive   ProductVariantStatus = "active"
	ProductVariantStatusInactive ProductVariantStatus = "inactive"
)

// Valid reports whether v is a known ProductVariantStatus value.
func (v ProductVariantStatus) Valid() bool {
	switch v {
	case ProductVariantStatusActive, ProductVariantStatusInactive:
		return true
	default:
		return false
	}
}

// ProductVariant is the generated type for inventory.product_variant.
type ProductVariant struct {
	ID           string               `json:"id"`
	OrgID        string               `json:"orgId"`
	AuthorID     string               `json:"authorId"`
	Deleted      bool                 `json:"deleted"`
	CreatedAt    time.Time            `json:"createdAt"`
	UpdatedAt    time.Time            `json:"updatedAt"`
	ProductId    string               `json:"productId"` // required
	Sku          string               `json:"sku"`       // required
	Name         string               `json:"name"`      // required
	Upc          string               `json:"upc"`
	Ean          string               `json:"ean"`
	Barcode      string               `json:"barcode"`
	Attributes   string               `json:"attributes"`
	BuyUomId     string               `json:"buyUomId"`
	StockUomId   string               `json:"stockUomId"`
	SellUomId    string               `json:"sellUomId"`
	StandardCost float64              `json:"standardCost"` // default=0
	ListPrice    float64              `json:"listPrice"`    // default=0
	Weight       float64              `json:"weight"`       // default=0
	AverageCost  float64              `json:"averageCost"`  // default=0
	Status       ProductVariantStatus `json:"status"`       // default=active
}
