// Code generated by kaizengo gen-types from apps/inventory/app.yaml; DO NOT EDIT.

package types

import "time"

// ProductTracking is the enum for product.tracking.
type ProductTracking string

const (
	ProductTrackingNone   ProductTracking = "none"
	ProductTrackingLot    ProductTracking = "lot"
	ProductTrackingSerial ProductTracking = "serial"
	ProductTrackingBoth   ProductTracking = "both"
)

// Valid reports whether v is a known ProductTracking value.
func (v ProductTracking) Valid() bool {
	switch v {
	case ProductTrackingNone, ProductTrackingLot, ProductTrackingSerial, ProductTrackingBoth:
		return true
	default:
		return false
	}
}

// ProductCostingMethod is the enum for product.costingMethod.
type ProductCostingMethod string

const (
	ProductCostingMethodFifo          ProductCostingMethod = "fifo"
	ProductCostingMethodLifo          ProductCostingMethod = "lifo"
	ProductCostingMethodMovingAverage ProductCostingMethod = "moving_average"
	ProductCostingMethodStandard      ProductCostingMethod = "standard"
)

// Valid reports whether v is a known ProductCostingMethod value.
func (v ProductCostingMethod) Valid() bool {
	switch v {
	case ProductCostingMethodFifo, ProductCostingMethodLifo, ProductCostingMethodMovingAverage, ProductCostingMethodStandard:
		return true
	default:
		return false
	}
}

// ProductDispatchStrategy is the enum for product.dispatchStrategy.
type ProductDispatchStrategy string

const (
	ProductDispatchStrategyFifo ProductDispatchStrategy = "fifo"
	ProductDispatchStrategyFefo ProductDispatchStrategy = "fefo"
	ProductDispatchStrategyLifo ProductDispatchStrategy = "lifo"
)

// Valid reports whether v is a known ProductDispatchStrategy value.
func (v ProductDispatchStrategy) Valid() bool {
	switch v {
	case ProductDispatchStrategyFifo, ProductDispatchStrategyFefo, ProductDispatchStrategyLifo:
		return true
	default:
		return false
	}
}

// ProductStatus is the enum for product.status.
type ProductStatus string

const (
	ProductStatusDraft        ProductStatus = "draft"
	ProductStatusActive       ProductStatus = "active"
	ProductStatusDiscontinued ProductStatus = "discontinued"
)

// Valid reports whether v is a known ProductStatus value.
func (v ProductStatus) Valid() bool {
	switch v {
	case ProductStatusDraft, ProductStatusActive, ProductStatusDiscontinued:
		return true
	default:
		return false
	}
}

// Product is the generated type for inventory.product.
type Product struct {
	ID               string                  `json:"id"`
	OrgID            string                  `json:"orgId"`
	AuthorID         string                  `json:"authorId"`
	Deleted          bool                    `json:"deleted"`
	CreatedAt        time.Time               `json:"createdAt"`
	UpdatedAt        time.Time               `json:"updatedAt"`
	Name             string                  `json:"name"` // required
	Code             string                  `json:"code"` // required
	Description      string                  `json:"description"`
	Category         string                  `json:"category"`
	Tracking         ProductTracking         `json:"tracking"`         // default=none
	CostingMethod    ProductCostingMethod    `json:"costingMethod"`    // default=moving_average
	DispatchStrategy ProductDispatchStrategy `json:"dispatchStrategy"` // default=fifo
	ShelfLifeDays    int                     `json:"shelfLifeDays"`    // default=0
	AttributeSchema  string                  `json:"attributeSchema"`
	Status           ProductStatus           `json:"status"` // default=active
	Notes            string                  `json:"notes"`
	Variants         []string                `json:"variants"`
}
