// Code generated by kaizengo gen-types from apps/inventory/app.yaml; DO NOT EDIT.

package types

import "time"

// ReorderRuleMethod is the enum for reorder_rule.method.
type ReorderRuleMethod string

const (
	ReorderRuleMethodMinMax      ReorderRuleMethod = "min_max"
	ReorderRuleMethodSafetyStock ReorderRuleMethod = "safety_stock"
	ReorderRuleMethodForecast    ReorderRuleMethod = "forecast"
)

// Valid reports whether v is a known ReorderRuleMethod value.
func (v ReorderRuleMethod) Valid() bool {
	switch v {
	case ReorderRuleMethodMinMax, ReorderRuleMethodSafetyStock, ReorderRuleMethodForecast:
		return true
	default:
		return false
	}
}

// ReorderRule is the generated type for inventory.reorder_rule.
type ReorderRule struct {
	ID             string            `json:"id"`
	OrgID          string            `json:"orgId"`
	AuthorID       string            `json:"authorId"`
	Deleted        bool              `json:"deleted"`
	CreatedAt      time.Time         `json:"createdAt"`
	UpdatedAt      time.Time         `json:"updatedAt"`
	VariantId      string            `json:"variantId"` // required
	LocationId     string            `json:"locationId"`
	Method         ReorderRuleMethod `json:"method"`         // default=safety_stock
	MinQty         float64           `json:"minQty"`         // default=0
	MaxQty         float64           `json:"maxQty"`         // default=0
	SafetyStock    float64           `json:"safetyStock"`    // default=0
	LeadTimeDays   int               `json:"leadTimeDays"`   // default=0
	AvgDailyDemand float64           `json:"avgDailyDemand"` // default=0
	ReorderPoint   float64           `json:"reorderPoint"`   // default=0
	QtyToOrder     float64           `json:"qtyToOrder"`     // default=0
}
