// Code generated by kaizengo gen-types from apps/inventory/app.yaml; DO NOT EDIT.

package types

import "time"

// RmaState is the enum for rma.state.
type RmaState string

const (
	RmaStateDraft         RmaState = "draft"
	RmaStateReceived      RmaState = "received"
	RmaStateDispositioned RmaState = "dispositioned"
	RmaStateClosed        RmaState = "closed"
)

// Valid reports whether v is a known RmaState value.
func (v RmaState) Valid() bool {
	switch v {
	case RmaStateDraft, RmaStateReceived, RmaStateDispositioned, RmaStateClosed:
		return true
	default:
		return false
	}
}

// RmaDisposition is the enum for rma.disposition.
type RmaDisposition string

const (
	RmaDispositionRestock    RmaDisposition = "restock"
	RmaDispositionRepair     RmaDisposition = "repair"
	RmaDispositionQuarantine RmaDisposition = "quarantine"
	RmaDispositionScrap      RmaDisposition = "scrap"
	RmaDispositionCredit     RmaDisposition = "credit"
)

// Valid reports whether v is a known RmaDisposition value.
func (v RmaDisposition) Valid() bool {
	switch v {
	case RmaDispositionRestock, RmaDispositionRepair, RmaDispositionQuarantine, RmaDispositionScrap, RmaDispositionCredit:
		return true
	default:
		return false
	}
}

// Rma is the generated type for inventory.rma.
type Rma struct {
	ID           string         `json:"id"`
	OrgID        string         `json:"orgId"`
	AuthorID     string         `json:"authorId"`
	Deleted      bool           `json:"deleted"`
	CreatedAt    time.Time      `json:"createdAt"`
	UpdatedAt    time.Time      `json:"updatedAt"`
	Name         string         `json:"name"`
	CustomerName string         `json:"customerName"` // required
	Origin       string         `json:"origin"`
	VariantId    string         `json:"variantId"` // required
	Quantity     float64        `json:"quantity"`  // required
	LocationId   string         `json:"locationId"`
	State        RmaState       `json:"state"`       // default=draft
	Disposition  RmaDisposition `json:"disposition"` // default=restock
	Notes        string         `json:"notes"`
}
