// Code generated by kaizengo gen-types from apps/inventory/app.yaml; DO NOT EDIT.

package types

import "time"

// StockLedgerSide is the enum for stock_ledger.side.
type StockLedgerSide string

const (
	StockLedgerSideDebit  StockLedgerSide = "debit"
	StockLedgerSideCredit StockLedgerSide = "credit"
)

// Valid reports whether v is a known StockLedgerSide value.
func (v StockLedgerSide) Valid() bool {
	switch v {
	case StockLedgerSideDebit, StockLedgerSideCredit:
		return true
	default:
		return false
	}
}

// StockLedger is the generated type for inventory.stock_ledger.
type StockLedger struct {
	ID         string          `json:"id"`
	OrgID      string          `json:"orgId"`
	AuthorID   string          `json:"authorId"`
	Deleted    bool            `json:"deleted"`
	CreatedAt  time.Time       `json:"createdAt"`
	UpdatedAt  time.Time       `json:"updatedAt"`
	PickingId  string          `json:"pickingId"`
	MoveId     string          `json:"moveId"`
	VariantId  string          `json:"variantId"`  // required
	LocationId string          `json:"locationId"` // required
	LotId      string          `json:"lotId"`
	SerialId   string          `json:"serialId"`
	Side       StockLedgerSide `json:"side"`     // required
	Quantity   float64         `json:"quantity"` // required
	UomId      string          `json:"uomId"`
	UnitCost   float64         `json:"unitCost"` // default=0
	Value      float64         `json:"value"`    // default=0
	OccurredAt time.Time       `json:"occurredAt"`
	Memo       string          `json:"memo"`
}
