// Code generated by kaizengo gen-types from apps/inventory/app.yaml; DO NOT EDIT.

package types

import "time"

// StockMoveState is the enum for stock_move.state.
type StockMoveState string

const (
	StockMoveStateDraft     StockMoveState = "draft"
	StockMoveStateDone      StockMoveState = "done"
	StockMoveStateCancelled StockMoveState = "cancelled"
)

// Valid reports whether v is a known StockMoveState value.
func (v StockMoveState) Valid() bool {
	switch v {
	case StockMoveStateDraft, StockMoveStateDone, StockMoveStateCancelled:
		return true
	default:
		return false
	}
}

// StockMove is the generated type for inventory.stock_move.
type StockMove struct {
	ID             string         `json:"id"`
	OrgID          string         `json:"orgId"`
	AuthorID       string         `json:"authorId"`
	Deleted        bool           `json:"deleted"`
	CreatedAt      time.Time      `json:"createdAt"`
	UpdatedAt      time.Time      `json:"updatedAt"`
	PickingId      string         `json:"pickingId"` // required
	VariantId      string         `json:"variantId"` // required
	FromLocationId string         `json:"fromLocationId"`
	ToLocationId   string         `json:"toLocationId"`
	Quantity       float64        `json:"quantity"` // required
	DoneQty        float64        `json:"doneQty"`  // default=0
	UomId          string         `json:"uomId"`
	LotId          string         `json:"lotId"`
	SerialId       string         `json:"serialId"`
	UnitCost       float64        `json:"unitCost"` // default=0
	State          StockMoveState `json:"state"`    // default=draft
}
