// Code generated by kaizengo gen-types from apps/inventory/app.yaml; DO NOT EDIT.

package types

import "time"

// StockLot is the generated type for inventory.stock_lot.
type StockLot struct {
	ID               string    `json:"id"`
	OrgID            string    `json:"orgId"`
	AuthorID         string    `json:"authorId"`
	Deleted          bool      `json:"deleted"`
	CreatedAt        time.Time `json:"createdAt"`
	UpdatedAt        time.Time `json:"updatedAt"`
	VariantId        string    `json:"variantId"` // required
	Name             string    `json:"name"`      // required
	ExpiryDate       string    `json:"expiryDate"`
	ManufacturedDate string    `json:"manufacturedDate"`
	Quantity         float64   `json:"quantity"` // default=0
}
