// Code generated by kaizengo gen-types from apps/inventory/app.yaml; DO NOT EDIT.

package types

import "time"

// StockSerialStatus is the enum for stock_serial.status.
type StockSerialStatus string

const (
	StockSerialStatusAvailable  StockSerialStatus = "available"
	StockSerialStatusReserved   StockSerialStatus = "reserved"
	StockSerialStatusInTransit  StockSerialStatus = "in_transit"
	StockSerialStatusSold       StockSerialStatus = "sold"
	StockSerialStatusScrapped   StockSerialStatus = "scrapped"
	StockSerialStatusQuarantine StockSerialStatus = "quarantine"
)

// Valid reports whether v is a known StockSerialStatus value.
func (v StockSerialStatus) Valid() bool {
	switch v {
	case StockSerialStatusAvailable, StockSerialStatusReserved, StockSerialStatusInTransit, StockSerialStatusSold, StockSerialStatusScrapped, StockSerialStatusQuarantine:
		return true
	default:
		return false
	}
}

// StockSerial is the generated type for inventory.stock_serial.
type StockSerial struct {
	ID         string            `json:"id"`
	OrgID      string            `json:"orgId"`
	AuthorID   string            `json:"authorId"`
	Deleted    bool              `json:"deleted"`
	CreatedAt  time.Time         `json:"createdAt"`
	UpdatedAt  time.Time         `json:"updatedAt"`
	VariantId  string            `json:"variantId"` // required
	LotId      string            `json:"lotId"`
	Serial     string            `json:"serial"` // required
	LocationId string            `json:"locationId"`
	Status     StockSerialStatus `json:"status"` // default=available
}
