// Code generated by kaizengo gen-types from apps/inventory/app.yaml; DO NOT EDIT.

package types

import "time"

// StockQuant is the generated type for inventory.stock_quant.
type StockQuant struct {
	ID          string    `json:"id"`
	OrgID       string    `json:"orgId"`
	AuthorID    string    `json:"authorId"`
	Deleted     bool      `json:"deleted"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
	VariantId   string    `json:"variantId"`  // required
	LocationId  string    `json:"locationId"` // required
	LotId       string    `json:"lotId"`
	Quantity    float64   `json:"quantity"`    // default=0
	ReservedQty float64   `json:"reservedQty"` // default=0
	UomId       string    `json:"uomId"`
	UnitCost    float64   `json:"unitCost"` // default=0
	Value       float64   `json:"value"`    // default=0
}
