// Code generated by kaizengo gen-types from apps/inventory/app.yaml; DO NOT EDIT.

package types

import "time"

// UomUomType is the enum for uom.uomType.
type UomUomType string

const (
	UomUomTypeReference UomUomType = "reference"
	UomUomTypeBigger    UomUomType = "bigger"
	UomUomTypeSmaller   UomUomType = "smaller"
)

// Valid reports whether v is a known UomUomType value.
func (v UomUomType) Valid() bool {
	switch v {
	case UomUomTypeReference, UomUomTypeBigger, UomUomTypeSmaller:
		return true
	default:
		return false
	}
}

// Uom is the generated type for inventory.uom.
type Uom struct {
	ID        string     `json:"id"`
	OrgID     string     `json:"orgId"`
	AuthorID  string     `json:"authorId"`
	Deleted   bool       `json:"deleted"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
	Name      string     `json:"name"`     // required
	Symbol    string     `json:"symbol"`   // required
	GroupId   string     `json:"groupId"`  // required
	Ratio     float64    `json:"ratio"`    // default=1, required
	Rounding  float64    `json:"rounding"` // default=1e-06
	UomType   UomUomType `json:"uomType"`  // default=reference
}
