// Code generated by kaizengo gen-types from apps/inventory/app.yaml; DO NOT EDIT.

package types

import "time"

// UomGroup is the generated type for inventory.uom_group.
type UomGroup struct {
	ID        string    `json:"id"`
	OrgID     string    `json:"orgId"`
	AuthorID  string    `json:"authorId"`
	Deleted   bool      `json:"deleted"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	Name      string    `json:"name"` // required
	Uoms      []string  `json:"uoms"`
}
