models:
  - name: uom
    fields:
      - name: name
        type: string
        required: true
      - name: symbol
        type: string
        required: true
      - name: groupId
        type: many2one
        relation: uom_group
        required: true
      - name: ratio
        type: number
        required: true
        default: 1
      - name: rounding
        type: number
        default: 0.000001
      - name: uomType
        type: enum
        values: [reference, bigger, smaller]
        default: reference
