// Code generated by kaizengo gen-types from apps/appman/app.yaml; DO NOT EDIT.

package types

import "time"

// AppStatus is the enum for app.status.
type AppStatus string

const (
	AppStatusAvailable AppStatus = "available"
	AppStatusInstalled AppStatus = "installed"
	AppStatusUpgrade   AppStatus = "upgrade"
	AppStatusSystem    AppStatus = "system"
)

// Valid reports whether v is a known AppStatus value.
func (v AppStatus) Valid() bool {
	switch v {
	case AppStatusAvailable, AppStatusInstalled, AppStatusUpgrade, AppStatusSystem:
		return true
	default:
		return false
	}
}

// App is the generated type for appman.app.
type App struct {
	ID               string    `json:"id"`
	OrgID            string    `json:"orgId"`
	AuthorID         string    `json:"authorId"`
	Deleted          bool      `json:"deleted"`
	CreatedAt        time.Time `json:"createdAt"`
	UpdatedAt        time.Time `json:"updatedAt"`
	Name             string    `json:"name"`  // required
	Title            string    `json:"title"` // required
	Summary          string    `json:"summary"`
	Version          string    `json:"version"`
	InstalledVersion string    `json:"installedVersion"`
	Installed        bool      `json:"installed"`
	Loaded           bool      `json:"loaded"`
	AutoInstall      bool      `json:"autoInstall"`
	Upgrade          bool      `json:"upgrade"`
	Status           AppStatus `json:"status"` // default=available
	Depends          string    `json:"depends"`
}
